# Generated by Django 6.0.2 on 2026-03-26 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('cosmetics', 'Декор'), ('weapon', 'Зброя'), ('decals', 'Декалі')], default='', max_length=20),
        ),
    ]
