# Generated by Django 6.0.2 on 2026-04-16 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='products/no_foto.jpg', upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_type',
            field=models.CharField(choices=[('Tool', 'Tool'), ('Weapon', 'Weapon'), ('Gun', 'Gun'), ('Other', 'Other'), ('Clothes', 'Clothes'), ('BuildingMaterial', 'BuildingMaterial')], default='', max_length=40),
        ),
    ]
