# Generated by Django 6.0.2 on 2026-04-16 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_product_image_alter_item_item_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default='items/no_foto.jpg', upload_to='items/'),
        ),
    ]
