# Generated by Django 6.0.2 on 2026-05-09 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_profile_user_reviw_delete_rating'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reviw',
            new_name='Review',
        ),
    ]
