# Generated by Django 6.0.2 on 2026-05-14 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_profile_email_alter_item_item_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='isPaid',
        ),
    ]
