# Generated by Django 6.0.2 on 2026-05-21 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_passwordresetcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_type',
            field=models.CharField(choices=[('Gun', 'Gun'), ('Melee Weapon', 'Melee Weapon'), ('Armor', 'Armor'), ('Other', 'Other')], default='', max_length=40),
        ),
    ]
