# Generated by Django 6.0.2 on 2026-05-21 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_item_item_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='achievements',
            field=models.ManyToManyField(blank=True, null=True, to='main.achievement'),
        ),
    ]
